print("How many pennies do you have?")
pennies = input()
print("How many nickels do you have?")
nickels = input()
print("How many dimes do you have?")
dimes = input()
print("How many quarters do you have?")
quarters = input()
print("How many fifty-cent-pieces do you have?")
fcps = input()
change = pennies+(5 * nickels)+(10 * dimes)+(25 * quarters)+(50 * fcps)
print("You have "+str(change)+" cents.")